import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import argparse
import os

def visualize_evolution(csv_path: str, output_path: str):
    """
    Visualize the evolution of Modularity vs Topic Overlap.
    """
    if not os.path.exists(csv_path):
        print(f"Error: CSV file not found at {csv_path}")
        return

    # Load the results generated by IterativeOrchestrator
    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        print(f"Error reading CSV: {e}")
        return

    # Check if 'topic_overlap' exists, if not calculate it from separation
    if 'topic_overlap' not in df.columns:
        print("Note: 'topic_overlap' column missing. Calculating from 'topic_separation'.")
        # Assuming topic_separation is Cosine Distance (0 to 1)
        if 'topic_separation' in df.columns:
            df['topic_overlap'] = 1.0 - df['topic_separation']
        else:
            print("Error: neither 'topic_overlap' nor 'topic_separation' columns found.")
            return

    # Create a dual-axis plot
    fig, ax1 = plt.subplots(figsize=(10, 6))

    color = 'tab:blue'
    ax1.set_xlabel('Iteration')
    ax1.set_ylabel('Modularity (Structure)', color=color)
    ax1.plot(df['iteration'], df['modularity'], color=color, marker='o', label='Modularity')
    ax1.tick_params(axis='y', labelcolor=color)
    ax1.grid(True, alpha=0.3)

    ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis

    color = 'tab:red'
    ax2.set_ylabel('Topic Embedding Overlap (Semantics)', color=color)
    # We expect Overlap to DECREASE as Modularity INCREASES if topics are becoming distinct
    ax2.plot(df['iteration'], df['topic_overlap'], color=color, marker='x', linestyle='--', label='Topic Overlap')
    ax2.tick_params(axis='y', labelcolor=color)

    plt.title('Evolution of Structural Modularity vs. Semantic Topic Overlap')
    fig.tight_layout()
    
    # Save the plot
    plt.savefig(output_path)
    print(f"Plot saved to {output_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Visualize Modularity vs Topic Overlap evolution.")
    parser.add_argument("--csv", default="output/iterative_experiment_results.csv", help="Path to the results CSV")
    parser.add_argument("--output", default="output/modularity_vs_overlap.png", help="Path to save the output image")
    
    args = parser.parse_args()
    visualize_evolution(args.csv, args.output)
