"""Visualization utilities for analytics outputs."""

import logging
import os
from typing import Dict, Optional, List, Any

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import seaborn as sns
import pandas as pd

logger = logging.getLogger(__name__)

def plot_evolution_metrics(csv_path: str, output_path: str) -> None:
    """
    Visualize the evolution of Modularity vs Topic Overlap.
    """
    from graphgen.analytics.plot_style import apply_thesis_style
    apply_thesis_style()

    if not os.path.exists(csv_path):
        logger.error("CSV file not found at %s", csv_path)
        return

    # Load the results generated by IterativeOrchestrator
    try:
        df = pd.read_csv(csv_path)
    except Exception:
        logger.exception("Error reading CSV: %s", csv_path)
        return

    # Check if 'topic_overlap' exists, if not calculate it from separation
    if 'topic_overlap' not in df.columns:
        logger.info("Column 'topic_overlap' missing. Calculating from 'topic_separation'.")
        # Assuming topic_separation is Cosine Distance (0 to 1)
        if 'topic_separation' in df.columns:
            df['topic_overlap'] = 1.0 - df['topic_separation']
        else:
            logger.error("Neither 'topic_overlap' nor 'topic_separation' columns found.")
            return

    # Create a dual-axis plot
    fig, ax1 = plt.subplots(figsize=(9, 5.5))

    color = 'tab:blue'
    ax1.set_xlabel('Iteration')
    ax1.set_ylabel('Modularity (Structure)', color=color)
    ax1.plot(df['iteration'], df['modularity'], color=color, marker='o', label='Modularity')
    ax1.tick_params(axis='y', labelcolor=color)
    ax1.grid(True, alpha=0.3)

    ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis

    color = 'tab:red'
    ax2.set_ylabel('Topic Embedding Overlap (Semantics)', color=color)
    # We expect Overlap to DECREASE as Modularity INCREASES if topics are becoming distinct
    ax2.plot(df['iteration'], df['topic_overlap'], color=color, marker='x', linestyle='--', label='Topic Overlap')
    ax2.tick_params(axis='y', labelcolor=color)

    plt.title('Evolution of Structural Modularity vs. Semantic Topic Overlap')
    fig.tight_layout()
    
    # Save the plot
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    plt.savefig(output_path, dpi=300)
    plt.close()
    logger.info("Evolution plot saved to %s", output_path)


def plot_topic_heatmap(
    topic_embeddings: Dict[str, np.ndarray], 
    topic_labels: Dict[str, str],
    output_path: str,
    title: str = "Topic Similarity Heatmap"
) -> None:
    """
    Generate and save a heatmap of topic similarity.
    """
    from graphgen.analytics.plot_style import apply_thesis_style, truncate_label
    apply_thesis_style()

    try:
        if not topic_embeddings:
            logger.info("Skipping heatmap: no topic embeddings available.")
            return

        sorted_ids = sorted(topic_embeddings.keys())
        matrix = np.vstack([topic_embeddings[tid] for tid in sorted_ids])
        labels = [truncate_label(topic_labels.get(tid, tid), 20) for tid in sorted_ids]
        
        # Calculate similarity
        from sklearn.metrics.pairwise import cosine_similarity
        sim_matrix = cosine_similarity(matrix)
        
        plt.figure(figsize=(10, 8))
        sns.heatmap(sim_matrix, xticklabels=labels, yticklabels=labels, cmap="YlOrRd")
        plt.title(title)
        plt.tight_layout()
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        plt.savefig(output_path, dpi=300)
        plt.close()
        logger.info(f"Saved heatmap to {output_path}")
        
    except Exception:
        logger.exception("Failed to plot heatmap.")

def generate_interactive_explorer(
    graph: nx.DiGraph, 
    output_path: str,
    communities: Optional[Dict[str, int]] = None
) -> None:
    """
    Generate an interactive HTML visualization using PyVis with search capability.
    """
    try:
        from pyvis.network import Network  # type: ignore[import-not-found]
    except ImportError:
        logger.warning("PyVis not installed. Skipping interactive explorer.")
        return

    # Create network
    net = Network(height="750px", width="100%", bgcolor="#ffffff", font_color="black")
    net.force_atlas_2based()
    
    # Add nodes and edges
    # Filter for Entities and Communities only (skip chunks to reduce noise)
    valid_types = {'ENTITY_CONCEPT', 'COMMUNITY', 'SUBCOMMUNITY'}
    
    display_graph = nx.DiGraph()
    
    for n, data in graph.nodes(data=True):
        if data.get('node_type') in valid_types:
            # Color by community
            color = "#97c2fc"
            if communities and n in communities:
                import matplotlib.colors as mcolors
                comm_id = communities[n]
                # Generate color from hash
                color = list(mcolors.TABLEAU_COLORS.values())[comm_id % 10]
                
            label = data.get('name', str(n))
            
            # Build comprehensive hover details
            title_parts = [f"<b>{label}</b>"]
            title_parts.append(f"Type: {data.get('node_type', 'Unknown')}")
            
            # Add description if available
            if 'description' in data and data['description']:
                desc = data['description']
                # Show full description on hover
                title_parts.append(f"<br><b>Description:</b> {desc}")
            
            # Add chunk IDs if available
            if 'chunk_ids' in data and data['chunk_ids']:
                chunk_count = len(data['chunk_ids']) if isinstance(data['chunk_ids'], list) else 1
                title_parts.append(f"<br><b>Chunks:</b> {chunk_count}")
            
            # Add any other metadata
            excluded_keys = {'name', 'node_type', 'description', 'chunk_ids', 'pos', 'embedding'}
            for key, value in data.items():
                if key not in excluded_keys and value is not None:
                    # Format the value nicely
                    if isinstance(value, (list, tuple)):
                        if value:
                            title_parts.append(f"<br><b>{key.replace('_', ' ').title()}:</b> {len(value)} items")
                    elif isinstance(value, dict):
                        if value:
                            title_parts.append(f"<br><b>{key.replace('_', ' ').title()}:</b> {len(value)} entries")
                    elif isinstance(value, (int, float, str, bool)):
                        title_parts.append(f"<br><b>{key.replace('_', ' ').title()}:</b> {value}")
            
            title = "".join(title_parts)
            net.add_node(n, label=label, title=title, color=color, group=communities.get(n, 0) if communities else 0)

    for u, v, data in graph.edges(data=True):
        if u in net.get_nodes() and v in net.get_nodes():
            # Build edge label from edge data
            edge_label = data.get('relation_type', data.get('type', ''))
            
            # Add score if available
            if 'score' in data:
                score = data['score']
                if isinstance(score, float):
                    edge_label += f" ({score:.2f})"
                else:
                    edge_label += f" ({score})"
            
            # Build edge title (hover text)
            edge_title_parts = []
            if 'relation_type' in data or 'type' in data:
                edge_title_parts.append(f"<b>Relation:</b> {data.get('relation_type', data.get('type', 'Unknown'))}")
            if 'score' in data:
                edge_title_parts.append(f"<br><b>Score:</b> {data['score']}")
            if 'weight' in data:
                edge_title_parts.append(f"<br><b>Weight:</b> {data['weight']}")
            
            # Add any other edge metadata
            excluded_edge_keys = {'relation_type', 'type', 'score', 'weight'}
            for key, value in data.items():
                if key not in excluded_edge_keys and value is not None:
                    if isinstance(value, (int, float, str, bool)):
                        edge_title_parts.append(f"<br><b>{key.replace('_', ' ').title()}:</b> {value}")
            
            edge_title = "".join(edge_title_parts) if edge_title_parts else None
            
            net.add_edge(u, v, label=edge_label, title=edge_title)

    # Inject custom search javascript
    # This is a bit hacky but standard for adding search to PyVis
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    net.save_graph(output_path)
    
    # Post-process HTML to add search bar
    with open(output_path, 'r', encoding='utf-8') as f:
        html = f.read()
        
    search_script = """
    <div id="search-container" style="position: absolute; top: 10px; left: 10px; z-index: 1000;">
        <input type="text" id="node-search" placeholder="Search entities..." onkeyup="searchNodes()">
        <div id="search-results" style="max-height: 200px; overflow-y: auto; background: white; border: 1px solid #ddd;"></div>
    </div>
    <script type="text/javascript">
        function searchNodes() {
            var input = document.getElementById("node-search");
            var filter = input.value.toUpperCase();
            var nodes = network.body.data.nodes.get();
            var resultsDiv = document.getElementById("search-results");
            resultsDiv.innerHTML = "";
            
            if (filter === "") return;
            
            var matched = nodes.filter(n => n.label && n.label.toUpperCase().includes(filter));
            
            matched.forEach(node => {
                var div = document.createElement("div");
                div.style.padding = "5px";
                div.style.cursor = "pointer";
                div.innerText = node.label;
                div.onclick = function() {
                    network.focus(node.id, {
                        scale: 1.5,
                        animation: true
                    });
                };
                resultsDiv.appendChild(div);
            });
        }
    </script>
    """
    
    # Insert before </body>
    if "</body>" in html:
        html = html.replace("</body>", f"{search_script}</body>")
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)
            
    logger.info(f"Saved interactive explorer to {output_path}")

def plot_node2vec_impact(
    results_history: List[Dict[str, Any]],
    output_path: str
) -> None:
    """
    Generate and save a plot comparing Baseline vs Node2Vec modularity.
    """
    from graphgen.analytics.plot_style import apply_thesis_style
    apply_thesis_style()

    try:
        if len(results_history) < 2:
            logger.info("Skipping Node2Vec plot: need at least 2 iterations.")
            return
        
        plt.figure(figsize=(9, 5.5))
        
        df = pd.DataFrame(results_history)
        iterations = df['iteration']
        modularity = df['modularity']
        baseline = df['modularity_baseline']
        
        plt.plot(iterations, modularity, marker='o', label='Node2Vec Modularity', linewidth=2, color='#1f77b4')
        plt.plot(iterations, baseline, marker='s', label='Baseline Modularity', linewidth=2, linestyle='--', color='#ff7f0e')
        
        plt.title('Impact of Node2Vec on Community Modularity', fontsize=16)
        plt.xlabel('Iteration', fontsize=12)
        plt.ylabel('Modularity', fontsize=12)
        plt.legend(fontsize=10)
        plt.xticks(iterations)
        
        # Add annotations for delta
        for i, (m, b) in enumerate(zip(modularity, baseline)):
            delta = m - b
            plt.annotate(f'{delta:+.3f}', 
                         xy=(iterations[i], m), 
                         xytext=(0, 10), 
                         textcoords='offset points',
                         ha='center', 
                         color='green' if delta > 0 else 'red',
                         fontsize=9)
        
        plt.tight_layout()
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        plt.savefig(output_path, dpi=300)
        plt.close()
        logger.info(f"Saved Node2Vec impact plot to {output_path}")
        
    except Exception:
        logger.exception("Failed to plot Node2Vec impact.")


if __name__ == "__main__":
    import argparse
    from graphgen.utils.logging import configure_logging
    
    configure_logging()
    parser = argparse.ArgumentParser(description="Visualize Modularity vs Topic Overlap evolution.")
    parser.add_argument("--csv", default="output/iterative_experiment_results.csv", help="Path to the results CSV")
    parser.add_argument("--output", default="output/modularity_vs_overlap.png", help="Path to save the output image")
    
    args = parser.parse_args()
    plot_evolution_metrics(args.csv, args.output)

def plot_community_centrality(
    centrality_data: Dict[str, Dict[str, List[Dict[str, Any]]]],
    output_dir: str,
    top_k: int = 5,
) -> None:
    """
    Generate academic-quality bar charts for top entities by centrality per community.
    One figure per community, with one subplot row per centrality measure.
    """
    from graphgen.analytics.plot_style import (
        apply_thesis_style, truncate_label, CENTRALITY_PALETTE,
    )
    apply_thesis_style()

    try:
        os.makedirs(output_dir, exist_ok=True)

        for comm_id, measures in centrality_data.items():
            if not measures:
                continue

            measure_names = list(measures.keys())
            n = len(measure_names)

            fig, axes = plt.subplots(n, 1, figsize=(7, 1.6 * n + 1.2), sharex=False)
            if n == 1:
                axes = [axes]

            fig.suptitle(
                f"Community {comm_id} — Top Entities by Centrality",
                fontsize=12, fontweight="bold", y=1.0,
            )

            for idx, (ax, measure) in enumerate(zip(axes, measure_names)):
                entities = measures[measure][:top_k]
                names = [truncate_label(e["name"]) for e in reversed(entities)]
                scores = [e["score"] for e in reversed(entities)]
                color = CENTRALITY_PALETTE[idx % len(CENTRALITY_PALETTE)]

                ax.barh(names, scores, color=color, edgecolor="white", linewidth=0.4)
                ax.set_title(measure.replace("_", " ").title(), fontsize=10, pad=4)
                ax.tick_params(axis="y", labelsize=8)
                ax.tick_params(axis="x", labelsize=8)
                ax.set_xlabel("Score", fontsize=9)

            fig.tight_layout(rect=[0, 0, 1, 0.97])
            fig.savefig(
                os.path.join(output_dir, f"community_{comm_id}_centrality.png"),
                dpi=300,
            )
            plt.close(fig)

        logger.info("Saved community centrality plots to %s", output_dir)

    except Exception:
        logger.exception("Failed to plot community centrality.")


def plot_global_centrality(
    centrality_data: Dict[str, List[Dict[str, Any]]],
    output_dir: str,
    top_k: int = 10,
) -> None:
    """
    Generate an academic-quality figure showing top entities by each centrality
    measure across the entire graph.  One subplot row per measure.
    """
    from graphgen.analytics.plot_style import (
        apply_thesis_style, truncate_label, CENTRALITY_PALETTE,
    )
    apply_thesis_style()

    try:
        if not centrality_data:
            return

        measure_names = list(centrality_data.keys())
        n = len(measure_names)

        fig, axes = plt.subplots(n, 1, figsize=(7, 2.0 * n + 1.2), sharex=False)
        if n == 1:
            axes = [axes]

        fig.suptitle(
            "Global Entity Centrality Rankings",
            fontsize=13, fontweight="bold", y=1.0,
        )

        for idx, (ax, measure) in enumerate(zip(axes, measure_names)):
            entities = centrality_data[measure][:top_k]
            names = [truncate_label(e["name"]) for e in reversed(entities)]
            scores = [e["score"] for e in reversed(entities)]
            color = CENTRALITY_PALETTE[idx % len(CENTRALITY_PALETTE)]

            ax.barh(names, scores, color=color, edgecolor="white", linewidth=0.4)
            ax.set_title(measure.replace("_", " ").title(), fontsize=10, pad=4)
            ax.tick_params(axis="y", labelsize=8)
            ax.tick_params(axis="x", labelsize=8)
            ax.set_xlabel("Score", fontsize=9)

        os.makedirs(output_dir, exist_ok=True)
        fig.tight_layout(rect=[0, 0, 1, 0.97])
        fig.savefig(os.path.join(output_dir, "global_centrality.png"), dpi=300)
        plt.close(fig)

        logger.info("Saved global centrality plot to %s", output_dir)

    except Exception:
        logger.exception("Failed to plot global centrality.")
